name: szakdolgozat

services:
  mysql-d47bep:
    image: mariadb:10.9
    container_name: mysql-d47bep
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: a
    volumes:
      - mysql-d47bep:/var/lib/mysql

  adminer-local:
    image: adminer
    container_name: adminer-local
    ports:
      - "29082:8080"
    environment:
      - ADMINER_DESIGN=lucas-sandery
      - ADMINER_DEFAULT_SERVER=mysql-d47bep
    depends_on:
      - mysql-d47bep

  fastapi:
    build:
      context: .. # Set the root project directory as the build context
      dockerfile: .docker/Dockerfile # Path to the Dockerfile inside the .docker folder
    container_name: fastapi-service
    ports:
      - "8000:8000"
    volumes:
      - ../python:/app # Map the "python" folder to /app inside the container
    depends_on:
      - mysql-d47bep

volumes:
  mysql-d47bep:
    driver: local
